### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by Talent30** [jolbol1/jolly-ui#14]
Hi, there.

This project and shadcnui are amazing. It makes so easy for people to migrate from one ui lib to another and keep the customisability at the same time.

I see this project is still at initial stage, would be nice you can put out a list of work items so that the community can submit PRs accordingly. Something like https://github.com/fabian-hiller/valibot/issues/287

**Comment by jolbol1** [comment]
Sorry for the late response, but super busy at the moment. 

This is a really good suggestion and I'll get round to it soon hopefully, as there is a few areas I am not sure I have the time to tackle on my own. Thanks!
