### ISSUE TITLE
Error when trying to install components by CLI

### ISSUE THREAD

**Issue by jucian0** [jolbol1/jolly-ui#30]
Hey, thanks for this amazing option to use react aria components, I've been trying to use it, but I always get this error:

`➜  pnpm dlx @sly-cli/sly add jolly-ui button

Packages: +78
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 100, reused 74, downloaded 4, added 78, done
Library/Caches/pnpm/dlx/wir6pp3fuan2dhdnga36uy5t6u/18f1504216a-3f66/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall scriptLibrary/Caches/pnpm/dlx/wir6pp3fuan2dhdnga36uy5t6u/18f1504216a-3f66/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 565ms
Could not connect to the registry at https://sly-cli.fly.dev/registry/index.json.
Check to see if the registry is running, or provide a custom URL by setting the REGISTRY_URL environment variable.`

**Comment by jolbol1** [comment]
This appears to be working for me still, did this resolve itself?

If not can you access: https://sly-cli.fly.dev/registry/index.json 

Does it respond with JSON data?

**Comment by jolbol1** [comment]
Hello, havent heard back in a month, marking as stale.
