### ISSUE TITLE
Failed intallation on Windows 11

### ISSUE THREAD

**Issue by Erasmus001** [jolbol1/jolly-ui#31]
Jolly components fail to install on windows 11 when installing with Bun or any other package manager.

**Comment by jolbol1** [comment]
Do you get an error message? Seems to work for me on Windows still.

**Comment by Erasmus001** [comment]
I will try it again later

**Comment by Erasmus001** [comment]
Thanks for responding

**Comment by jolbol1** [comment]
Hello, haven't heard back in a month, marking as stale.
