### ISSUE TITLE
Sly registry for list-box points to grid-list

### ISSUE THREAD

**Issue by jacobparis** [jolbol1/jolly-ui#44]
I just tried to install the list-box component and got grid-list instead, probably a copy/paste error in the registry

<img width="286" alt="image" src="https://github.com/user-attachments/assets/f7944c57-deee-426a-aace-345e5ca3a72b">

**Comment by jolbol1** [comment]
Hi. thanks for catching this, should be fixed now thanks to @Lorde4Avalon
