### ISSUE TITLE
React hook form examples

### ISSUE THREAD

**Issue by zommerberg** [jolbol1/jolly-ui#50]
React hook form is widely used, I know react aria has its own form management but it is not as rich.

Are there any plans of adding examples with react-hook-form?

**Comment by zommerberg** [comment]
Closign this until https://github.com/adobe/react-spectrum/issues/6809 is resolved

**Comment by zommerberg** [comment]
I am reopening this one since a workaround now exists. 

https://github.com/adobe/react-spectrum/issues/6809#issuecomment-2266031613

**Comment by zommerberg** [comment]
But maybe its still better to wait until official solution from adobe...

**Comment by musjj** [comment]
Would love to see some react-hook-form examples, especially around date pickers. You can always dedicate a small segment on caveats (linking to the issue above), if general functionality still works.
