### ISSUE TITLE
New example with a unselectable radio element

### ISSUE THREAD

**Issue by zommerberg** [jolbol1/jolly-ui#51]
Usually if we want to display a radio element we use the react aria radio group. However often we need the ability to unselect a radio element. This however is not a valid HTML behavior since you cannot unselect a radio element. 

To make this work one need to use the react aria checkbox group component and style it as a radio element.

Here is a video example:

https://github.com/user-attachments/assets/fd3297b3-3c70-42a3-ae8c-6497af08b93c

To do this I've expanded the Checkbox from the tailwindExample to accpet a renderAs prop which allows me to render radioStyles instead of checkbox styles.
![image](https://github.com/user-attachments/assets/81b4c84a-87dd-46f8-b0b4-6439d7049191)

**Comment by jolbol1** [comment]
Thanks for this. Im not sure I would want to implement this / show this as an example as it does go against the web practices that React Aria Components, and my library aim to follow.

Thanks for showing your demo though as others can find this if they run into the same issue. Also to the others, If you think this is an example worth putting on the documentation, do let me know and maybe I will reconsider if enough people have this demand.

For others reference on the web standard:
> At all times, exactly one of the radio buttons in a set is checked. If none of the elements of a set of radio buttons specifies `CHECKED', then the user agent must check the first radio button of the set initially.

https://www.w3.org/TR/html401/interact/forms.html#radio
