### ISSUE TITLE
Popover props not being overridden

### ISSUE THREAD

**Issue by codiuscube** [jolbol1/jolly-ui#59]
I'm experiencing an issue with the Popover component where I'm unable to override the default values, for example, for the offset and containerPadding props.

**Popover component area**
```
const Popover = ({ className, offset = 10, containerPadding = 20, ...props }: AriaPopoverProps) => (
  <AriaPopover
    offset={offset}
    containerPadding={containerPadding}
    {...props}
  />
);
```

**Popover component instance**
```
<Popover
  triggerRef={triggerRef}
  containerPadding={0}
  offset={0}
  {...otherProps}
/>
```

**Expected behavior:**
The popover should render with the custom values for offset and containerPadding that are passed in.

**Actual behavior:**
The popover renders with the default values for offset and containerPadding instead of the custom values.

**Comment by jolbol1** [comment]
Hi this appears to be working for me?

Using the Popover from the installed component, I the use this demo:

```tsx
"use client"

import { Button } from "@/registry/default/ui/button"
import {
  Popover,
  PopoverDialog,
  PopoverTrigger,
} from "@/registry/default/ui/popover"
import { Switch } from "@/registry/default/ui/switch"

export function PopoverDemo() {
  return (
    <PopoverTrigger>
      <Button variant="outline">Settings</Button>
      <Popover offset={50} containerPadding={50}>
        <PopoverDialog>
          <div className="flex flex-col gap-4">
            <Switch defaultSelected>
              <div className="indicator" /> Wi-Fi
            </Switch>
            <Switch defaultSelected>
              <div className="indicator" /> Bluetooth
            </Switch>
            <Switch>
              <div className="indicator" /> Mute
            </Switch>
          </div>
        </PopoverDialog>
      </Popover>
    </PopoverTrigger>
  )
}
```
If I change offset to 50, I get: 
<img width="287" alt="Screenshot 2024-08-13 at 21 54 58" src="https://github.com/user-attachments/assets/25842d5c-57f1-4b10-9e59-aa05124f916e">

Container padding appears to work too. Just to confirm, container padding in React Aria Components is the minimum distance a popover needs from the element the popover is in. This usually means the browser window, so 50px will maintain at least 50px between the popover and the edge of the browser window. If you mean to control the padding inside the popover you can use tailwind for this.

**Comment by jolbol1** [comment]
Hi @codiuscube, I am closing this as I have not heard back and I believe this is working?

Feel free to reopen if you need more help.
