### ISSUE TITLE
shadcn config respected?

### ISSUE THREAD

**Issue by bugzpodder** [jolbol1/jolly-ui#60]
```
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@webapp/frontend/components/ui",
    "utils": "@webapp/frontend/utils/ui",
    "ui": "src/components/ui"
  }
}
```
are shadcn config like this respected? I've found that style (radix-ui/react-icons rather than lucide-react) and aliiases utils/ui doesn't seem to actually work, or is `component.json` ignored and all configs are in `sly.json`

looks like styles is being tracked in https://github.com/jacobparis-insiders/sly/issues/35, but how about aliases
also it doesn't like yarn and will try to use npm to install dependencies

**Comment by jolbol1** [comment]
Correct, was a bit limited with options from Sly in terms of reading the components.json.

This should be supported now via the new shadcn cli, let me know if you have any issues: https://www.jollyui.dev/docs/installation/cli
