### ISSUE TITLE
some cli components can't be installed

### ISSUE THREAD

**Issue by bugzpodder** [jolbol1/jolly-ui#62]
```
REGISTRY_URL=https://jollyui.dev/r npx shadcn@latest add checkbox-group

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Unexpected token '<', "<!DOCTYPE "... is not valid JSON

```
also happens with date-range-picker, datepicker, etc
also i see there are package manager copy options (yarn, bun, etc) which doesnt seem to be different (all copies npx)

**Comment by jolbol1** [comment]
Hi sorry for the issue! 

Seems like I need to update the doc install links for some components, for example checkbox-group is just installed via checkbox.

Does appear to be another issue though with some components that are valid saying the registry is not valid json, e.g textfield.

As for the package manager copy options, these appear to be working for me. Is there a specific page or is it all of them for you?

**Comment by jolbol1** [comment]
The commands should be fixed now, and installing seems to okay for me. The copy commands all seem to work as well, but let me know if theres a specific one thats broken.

Reopen if anymore issues 😃
