### ISSUE TITLE
Some components not 1-to-1 with shadcn/ui

### ISSUE THREAD

**Issue by brandonmcconnell** [jolbol1/jolly-ui#8]
Some components are not 1-to-1 with shadcn/ui.

In the case of the combobox ([shadcn](https://ui.shadcn.com/docs/components/combobox) | [jolly](https://www.jollyui.dev/docs/components/combobox)), for example, one is a field you can click and type into while the other acts more like a button.

I think it would be most helpful if both the components and examples led a 1:1 relationship to shadcn/ui, especially if the goal is to be a direct and more accessible alternative until shadcn/ui switches to using React Aria or similar.

**Comment by jolbol1** [comment]
I see the point. In the case of the combobox, it was actually the first reason the library started, as the shadcn implementation relies on cmdk and seemed bulky for the simpler stuff. 

I'll see if I can modify it to have a variant closer to shadcn and add some examples. If there's any other components let me know.

**Comment by jolbol1** [comment]
@brandonmcconnell for that you can change the prop menuTrigger to be "input". See Adobe [docs](https://react-spectrum.adobe.com/react-aria/ComboBox.html#:~:text=to%20be%20set.-,menuTrigger,-MenuTriggerAction)

I will considering making this the default behavior and if not at least ensuring there is an example or its well documented. 

Thanks for the input!

**Comment by brandonmcconnell** [comment]
@jolbol1 Thanks! I think it could really help to keep the baseline with consistent parity to [shadcn/ui](https://github.com/shadcn-ui/ui), as even slight differences could complicate a migration to [jolly-ui](https://github.com/jolbol1/jolly-ui) in the future, unless the goal is actually to keep this package standalone and not merge into [shadcn/ui](https://github.com/shadcn-ui/ui) at some point.

**Comment by jolbol1** [comment]
Hey @brandonmcconnell, I think it comes down to this:

To summarize and clarify the key points:
- All jolly-ui components will be built using React Aria, in contrast with shadcn/ui's use of Radix. This architectural difference makes it infeasible to have 100% parity in component composition and behaviour. But the styling system will remain the same, ensuring visual and CSS compatibility.
- At the same time, jolly-ui is its own independent library that aims to extend and complement shadcn/ui, especially by providing additional components built with React Aria that are missing from shadcn/ui currently. So it will have its own identity and life beyond just mirroring shadcn/ui.
- If shadcn/ui does switch from Radix to React Aria components in the future, jolly-ui would likely become obsolete. But in the meantime, it provides a valuable alternative for developers who prefer the React Aria component model.
- Any components added to shadcn, that utilise React Aria, I will make the version on JollyUI obsolete
- Any components that Jolly-UI has that shadcn does not, but later adds (without React Aria), I will rewrite to ensure the styling is the same.

Does this clear things up? Any more thoughts let me know!

**Comment by brandonmcconnell** [comment]
That makes a ton of sense! Thanks for clearing that up 🙂
